name: PR triggering

on:
  pull_request:
    types:
      - opened
      - reopened
    paths:
      - "!src/*.css"
      - "src/*tsx"

jobs:
  checking-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "hey there"