name: ENV variable scope

on:
  push:
    branches: [jackal]

env:
  GLOBAL_WF_VAR: "I am available everywhere"

jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      JOB_1_ONLY_VAR: "I am only inside Job 1"
    steps:
      - name: Testing Job 1 Scopes
        env:
          STEP_1_ONLY_VAR: "I am only inside Step 1"
        run: |
          echo "From Workflow Level: $GLOBAL_WF_VAR"
          echo "From Job 1 Level: $JOB_1_ONLY_VAR"
          echo "From Step 1 Level: $STEP_1_ONLY_VAR"
            
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Job 2 Scopes
        env:
          STEP_2_ONLY_VAR: "I am only inside Step 2"
        run: |
          echo "From Workflow Level: $GLOBAL_WF_VAR"
          echo "From Job 1 Level: $JOB_1_ONLY_VAR"
          echo "From Step 2 Level: $STEP_2_ONLY_VAR"